### ISSUE TITLE
cucumber-cpp does not work with the latest cucumber ruby version (3.1)

### ISSUE THREAD

**Issue by chuymax** [cucumber/cucumber-cpp#200] opened 2018-08-27 00:48 UTC
## Summary

Cucumber-cpp does not work with the latest cucumber-ruby version (3.1)

## Expected Behavior

Cucumber-cpp works with the latest cucumber-ruby version.

## Current Behavior

Compiling cucumber-cpp and running the examples+cucumber throw "undefined definition" messages.

## Possible Solution

Workaround:
1. Uninstall cucumber-ruby 3.1.2: sudo gem uninstall cucumber
2. Install cucumber-ruby 2.4: sudo gem install cucumber -v 2.4
3. Run cucumber from the examples/Calc, not from the project root as described in the readme instructions ("cd examples/Calc && cucumber ."), otherwise you'll still get undefined definitions, even with cucumber-ruby 2.4.

## Steps to Reproduce (for bugs)

1. Install ubuntu 18.04
2. Install dependencies with apt (boost, qt, g++, cmake, gtest, ruby)
3. Install bundler and cucumber-ruby with gem package manager (gem install bundler cucumber)
4. Follow the readme instructions to compile cucumber-cpp and examples
5. Run one of the examples

build/examples/Calc/BoostCalculatorSteps >/dev/null &
cucumber examples/Calc

6. Cucumber throws a bunch of undefined definitions

## Context & Motivation

I struggled for hours to run cucumber-cpp examples. What I am trying to accomplish? This issue to be fixed, and let other developers know (by having the doc changed) that cucumber-cpp does not work with the latest version of cucumber-ruby, so they don't waste hours of their time.

## Your Environment

* Version used: cucumber-cpp v0.5.1-g79e92de
* Operating System and version: Ubuntu 18.04 LTS Server
* Link to your project: N/A

**Comment by paoloambrosio** [comment] 2018-08-27 06:39
I believe it is a duplicate of #194 and #179.

It was a bug in Cucumber-Ruby:
 - Issue: https://github.com/cucumber/cucumber-ruby/issues/1183
 - PR: https://github.com/cucumber/cucumber-ruby-wire/pull/15

It looks like the fix is targeting Cucumber-Ruby 4.0.0 yet unreleased.

**Closed** 2018-10-20 08:18 UTC
